# Play nice with Docker on OSX
host: 0.0.0.0

name: Charles Fyfe
title: charles.uno
description: "probably fine"
url: 'http://charles.uno'
baseurl: ''
github: 'https://github.com/charles-uno'
author:
    name: Charles Fyfe
logo: null
permalink: /:title/
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - gh-pages
sass:
  sass_dir: /assets/_sass
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - CNAME
kramdown:
  input: GFM
