name: char1es
htmlname: <span class="title-base">char</span><span class="title-accent">1</span><span class="title-base">es</span>
description: ''
url: 'http://charles.uno'
baseurl: ''
github: 'https://github.com/chizarlicious'
permalink: /:title/
markdown: kramdown
cdn: ''
gems:
  - jekyll-sitemap
  - jekyll-feed
sass:
  sass_dir: /assets/_sass
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - CNAME
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
kramdown:
  input: GFM
