# Play nice with Docker on OSX
host: 0.0.0.0

name: Charles Fyfe
title: Charles Fyfe
description: "Personal website of Charles Fyfe"
url: 'https://charles.uno'
baseurl: ''
github: 'https://github.com/charles-uno'
author:
    name: Charles Fyfe
permalink: /:title/
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - gh-pages
sass:
  sass_dir: /assets/_sass
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - CNAME
markdown: kramdown
kramdown:
  input: GFM
