# Docker for OSX uses a VM so we need 0.0.0.0 instead of 127.0.0.1
host: 0.0.0.0

name: Charles Fyfe
title: charles
description: "food, games, science, politics"
url: 'http://charles.uno'
baseurl: ''
github: 'https://github.com/charles-uno'
author:
    name: Charles Fyfe
    twitter: charles_uno
twitter:
  username: charles_uno
facebook:
    publisher: https://www.facebook.com/charles.a.mceachern
logo: null
social:
  name: Charles Fyfe
  links:
    - https://twitter.com/charles_uno
    - https://www.facebook.com/charles.a.mceachern
    - https://www.linkedin.com/in/charlesmceachern
    - https://github.com/charles-uno
permalink: /:title/
markdown: kramdown
cdn: ''
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - gh-pages
sass:
  sass_dir: /assets/_sass
  style: :compressed
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - CNAME
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
kramdown:
  input: GFM
